### ISSUE TITLE
Example code not working with jsondown

### ISSUE THREAD

**Issue by csterritt** [PsychoLlama/gun-level#19]
Hey - thanks for doing this. I'm trying to run the demo:

```js
// Import the gun library
var Gun = require('gun');
require('gun-level');

// Import the two libraries
const levelup = require('levelup')
const jsondown = require('jsondown')

// Create a new level instance which saves
// to the `data/` folder.
const levelDB = levelup('data', {
    db: jsondown,
})

// Create a new gun instance
var gun = Gun({
    level: levelDB,
});

// Read `greetings`, saving it to a variable.
var greetings = gun.get('greetings');

// Update the value on `greetings`.
greetings.put({
    hello: 'world',
})
```
And it's doing two surprising things. First, it still writes the 'data.json' file, and second, it writes nothing in the 'data' directory (although it creates it).

This is on macOS 10.12.2, using node v6.9.1, gun 0.3.9991, and gun-level 4.0.1.

What am I doing wrong?  Thanks!

**Comment by amark** [comment]
What version are you using of gun? 0.5 or master/stable?

**Comment by amark** [comment]
Oh, you already answered that, sorry. Give me a minute...

**Comment by amark** [comment]
I keep getting errors with levelDOWN by itself: `LevelDOWN (Module version mismatch. Expected 48, got 47`. I'll let you know when I have figured out what is going on.

**Comment by amark** [comment]
@csterritt could you test to see if this works?

In a new directory do

`mkdir node_modules`

then

`npm install gun gun-level leveldown`

check to make sure that a bunch of folders exist by `ls node_modules` (if it is empty something is wrong).

Then copy and paste this into a file called `level.js`:

```
// Imports the `Gun` library
const Gun = require('gun')

// Imported for side effects, adds level adapters.
require('gun-level')

// Import the two libraries
const levelup = require('levelup')
const leveldown = require('leveldown')

// Create a new level instance which saves
// to the `data/` folder.
const levelDB = levelup('data', {
    db: leveldown,
})

const gun = new Gun({
    file: false,
    level: levelDB,
})

const bob = gun.get('bob').put({ name: 'Bob' })
const dave = gun.get('dave').put({ name: 'Dave' })

// Write a fun circular reference.
bob.path('friend').put(dave)
dave.path('friend').put(bob)

// Print the data!
bob.path('friend.name').val()
bob.path('friend.friend.name').val()
```

Run it with

`node level.js`

There should be no errors. You should see the writes. And you can check it worked correctly by:

`ls data`

It should print some junk.

Did this work?

**Comment by csterritt** [comment]
For whatever it's worth, I'm trying to stay JS-only, so I'm using jsondown, not leveldown.

Here's my `package.json` file:

```js
{
  "name": "gun_test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "gun": "^0.3.9991",
    "gun-level": "^4.0.1",
    "jsondown": "^0.1.1",
    "levelup": "^1.3.3"
  }
}
```

**Comment by csterritt** [comment]
Hey, that worked!  I did change the 'leveldown' instances to 'jsondown', and it worked fine.  Thanks!

**Comment by amark** [comment]
@csterritt ahhh! That is awesome, I love staying to js-only too.

In that case... using the built in `data.json` of gun is gonna be just as good as jsondown because (from https://github.com/toolness/jsondown)...

> It also retains the contents of the entire JSON file in memory, so it's only really useful for debugging purposes and/or very small data stores that need just a pinch of persistence.

Which is the exact same warning we have on our data.json file.js module. So you aren't going to get any advantage using jsondown.

Note, moving forward (in 0.5?) I think that localStorage will be compatible with NodeJS localStorage polyfills. Which I think are pure JS.

**Comment by csterritt** [comment]
Thanks for the help, and the update.  I'll await 0.5 eagerly!

**Comment by PsychoLlama** [comment]
Sweet! Thanks for handling this issue @amark! :smile:
@csterritt did this resolve your issue?

**Comment by csterritt** [comment]
Yup, thanks.

**Comment by PsychoLlama** [comment]
Cool, closing for now. If you have any further problems, feel free to reopen!
