### ISSUE TITLE
I am trying to get gun-level to work with level-js in the browser

### ISSUE THREAD

**Issue by JonathanDDuncan** [PsychoLlama/gun-level#22]
This is code I have tried in Runkit [https://runkit.com/58470cf725386e0014684507/5886876a7bb1cd001392cc50](Runkit gun-level with level-js)

I get this error

> ReferenceError Stack Trace Viewer 
> ReferenceError: self is not defined
> new IDBStore in idb-wrapper/idbstore.js
> line 129, column 56
> Level._open in level-js/index.js
> line 37, column 14
> AbstractLevelDOWN.open in abstract-leveldown/abstract-leveldown.js
> line 28, column 17
> LevelUP.open in levelup/lib/levelup.js
> line 117, column 6
> new LevelUP in levelup/lib/levelup.js
> line 87, column 8
> [object Object].LevelUP in levelup/lib/levelup.js
> line 47, column 12
>  in this notebook
> line 13, column 17
> Code Node Startup Show Full Stack Trace...

But when trying to run it on my windows webpack setup I get a very different message

> Error in ./~/levelup/package.json
> Module parse failed: C:\Users\Jonathan\Documents\Freelance\Jehle\desconjugador\node_modules\levelup\package.json Unexpected token (2:9)
> You may need an appropriate loader to handle this file type.
> SyntaxError: Unexpected token (2:9)
>  @ ./~/levelup/lib/util.js 32:25-51

It seems to me it should just work but I am a bit new at this levelary stuff and not a ton of experience with node npm and wepack, I've just got the basics down.

Could you show me what I would need to do to get gun-level working with level-js.  My goal is to have gundb backed by indexeddb in the browser.
Thanks

**Comment by JonathanDDuncan** [comment]
I just figured out that RunKit is an in browser server environment, so obviously IndexedDb won't be available there.  But I would still like to get it to run in the browser.

**Comment by PsychoLlama** [comment]
> Note for future googlers and/or internet archaeologists: most of this conversation happened on issue #23.

I'll bet the errors are from the API changes between gun-level v3 and v4. With the code posted in issue #23, I got it to work just by switching the `require` to `level-js` instead of `fruitdown`:

```diff
const levelUp = require('levelup');
- const fruitdown = require('fruitdown');
+ const leveljs = require('level-js');

// Instantiate a new level database.
const level = levelUp('my-database-name', {
- 	db: fruitdown,
+ 	db: leveljs,
});
```

Lemme know if it works for you!

**Comment by JonathanDDuncan** [comment]
Yes I tried leveljs and it worked too.
Thanks
