### ISSUE TITLE
gun-level not working (with gun 0.7.4)

### ISSUE THREAD

**Issue by rsaccon** [PsychoLlama/gun-level#28]
I just tried out gun-level 0.5 and it does not work, but also does not give an error.

`const gundb = Gun({
  level: levelDB,
  file: false,
});`

`leveldb` itself works fine, I can put and get stuff into and out from it, but anything with gundb fails silently, e.g. after:

`gundb.get('foo').put({bar:'hello'});`

there is nothing in the actual database records representing that entry.

and when doing a query:

`gundb.get('bar').val(function(data){
  console.log("Hit:");
  console.log(data);
  })`

the callback does never gets called.

**Comment by amark** [comment]
This is bad, and probably my fault, haven't kept @PsychoLlama up to date lately. I'm out in SF right now, I'll try to check into this when I get back next week.

**Comment by PsychoLlama** [comment]
Indeed, it looks like gun has undergone low-level api changes since I last saw it. @amark we should collab soon.

Trying to get it working on my end, but I keep running into different error messages from gun internals (some related to uWS).

**Comment by amark** [comment]
Hmm, I haven't changed any of the wire spec or adapter interface since 0.5, although there are a couple annoying (but easy to port) breaking changes coming up in 0.8 or 0.9. What was the uWS error? Alex deleted versions which caused a lot of things to error, but latest should be resolved now so if it isn't I need to check/fix that.

I'm back in Utah now, if you want to catch up @PsychoLlama :) we never got together last time.

**Comment by sjones6** [comment]
hey @PsychoLlama , was chatting with @amark about gun-level's compatibility with GUN 0.8. He mentioned you were planning to patch the current issue. Do you know when that might be? Do you mind if I put a PR in if I'm able to get it working? Otherwise, I can wait...just don't know how long :)

**Comment by PsychoLlama** [comment]
Hey @sjones6! Mark showed me the API changes late last night, but I think the soonest I could tackle this issue is late Wednesday. If you get it working locally, by all means submit a PR!

**Comment by sjones6** [comment]
@PsychoLlama Heyo! Awesome sauce... I got it working tonight. Buuuut. It's ugly and needs some fixing. I hope to have something up later tomorrow that we could kick around.

**Comment by sjones6** [comment]
@PsychoLlama et al : PR #31 is up with fixes for Gun 0.8: https://github.com/PsychoLlama/gun-level/pull/31

**Comment by PsychoLlama** [comment]
Because @sjones6 is amazing, gun-level is now a thing that works! Installing `gun-level@v6.0.0` should resolve this issue. If y'all have any more trouble with it, we can re-open this issue.

Thanks for taking care of that, Spencer!
