### ISSUE TITLE
Consider to split main function into gun-levelup

### ISSUE THREAD

**Issue by thoka** [PsychoLlama/gun-level#3]
Gun-levelup could work in a backend agnostic mode.
The backend should have to be configured with a 'db' option (see https://github.com/Level/levelup#relationship-to-leveldown).

Gun-level's only job would be to initialize gun-levelup with the LevelDOWN level storage backend.

This way all kind of [storage back-ends](https://github.com/Level/levelup/wiki/Modules#storage) will be available.

**Comment by PsychoLlama** [comment]
Looks like I closed the issue through the wrong commit :grin: - here's [the link to the one that solved it](https://github.com/PsychoLlama/gun-level/commit/3cf88fc90f0b8f92a6592d2367fd9bb74ee66ce5)

**Comment by PsychoLlama** [comment]
That's awesome! It would be amazing if others could use their existing level modules with gun-level! I'll look into it and see what I can do to work with the existing ecosystem. Thanks for the tip off, I'll be sure to keep you informed!

**Comment by PsychoLlama** [comment]
Good news @thoka! I'm close to finishing a 2.0 for gun-level that gives users complete control over the storage configuration while keeping sensible defaults, among other notable improvements. With luck, I'll have it deployed sometime today :grinning:

**Comment by PsychoLlama** [comment]
@thoka the newest release now works fabulously with the level ecosystem. Is it okay if I close this issue?

**Comment by thoka** [comment]
Sure.
Am 30.11.2015 20:39 schrieb "Jesse Gibson" <notifications@github.com>:

**Comment by PsychoLlama** [comment]
Awesome. Thanks for your help!
