### ISSUE TITLE
file:false not respected by Gun

### ISSUE THREAD

**Issue by Stefdv** [PsychoLlama/gun-level#37]
I have it all setup and it's working :)
BUT  i named the data file 'level_data' in `const levelDB =levelup('level_data',{db:jsondown})`

It turns out that Gun is still creating the `data.json` file , so now 2 files are created.

**Comment by PsychoLlama** [comment]
Looks like Mark inadvertently removed the `opts.file === false` check in his file plugin ([source](https://github.com/amark/gun/commit/4db1ae9872b4ff38444bf92941acad488281f453)). As a workaround, try reverting to `v0.7.9`.

**Comment by PsychoLlama** [comment]
I've opened [a PR](https://github.com/amark/gun/pull/400) to gun. That should get the `file: false` option working again.

**Comment by Stefdv** [comment]
@PsychoLlama , @amark  I close this issue because its not an issu anymore. Mark explained how to configure Gun without file.js. 
Tx anyway Jesse 👍

**Comment by PsychoLlama** [comment]
Sure thing! Thanks for posting this. I didn't realize gun changed the API.

**Comment by amark** [comment]
Yeah sorry @psychollama, I made file be a generic option, not specific to file.js - in fact you would be proud of me, because server side I'm encouraging people to just use a modular approach!

**Comment by PsychoLlama** [comment]
@amark that makes me happy. Feel free to axe my PR if it's no longer relevant.
