### ISSUE TITLE
gun-level not working with gun 8.8

### ISSUE THREAD

**Issue by kavaro** [PsychoLlama/gun-level#38]
Express server crashes with error message:
```
gun-level/dist/Adapter/index.js:179
        gun._.root.on('in', {
           ^

TypeError: Cannot read property '_' of undefined
```

The code below works perfectly with the file adapter, but not with gun-level

Server code:
```
const express = require('express');
const path = require('path');
const favicon = require('serve-favicon');
const logger = require('morgan');
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');
const sassMiddleware = require('node-sass-middleware');
const levelup = require('levelup');
const leveldown = require('leveldown');
const Gun = require('gun/gun'); // this includes core, no defaults!
require('gun/lib/file');
require('gun/lib/path');
require('gun/lib/not');
require('gun/lib/ws');
require('gun/nts');
require('gun-level');

const app = express();
const publicDir = path.join(__dirname, 'public');

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(publicDir, 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: false}));
app.use(cookieParser());
app.use(sassMiddleware({
    src: publicDir,
    dest: publicDir,
    indentedSyntax: false, // true = .sass and false = .scss
    sourceMap: true
}));
//app.use(Gun.serve);
app.use(express.static(publicDir));

// catch 404 and forward to error handler
app.use(function (req, res, next) {
    const err = new Error('Not Found');
    err.status = 404;
    next(err);
});

// error handler
app.use(function (err, req, res, next) {
    // set locals, only providing error in development
    res.locals.message = err.message;
    res.locals.error = req.app.get('env') === 'development' ? err : {};

    // render the error page
    res.status(err.status || 500);
    res.render('error');
});

function normalizePort(val) {
    const port = parseInt(val, 10);

    if (isNaN(port)) {
        // named pipe
        return val;
    }

    if (port >= 0) {
        // port number
        return port;
    }

    return false;
}

const port = normalizePort(process.env.PORT || '3100');
app.set('port', port);

/**
 * Create HTTP server.
 */

const server = app.listen(port);

const levelDB = levelup('data', {
    db: leveldown
});

const gun = Gun({
    web: server,
    level: levelDB,
    file: false
});
```

As soon as the client (website, build with create-react-app setup) executes the following code, the server crashes with the error given above:

const Gun = require('gun/gun');
const peers = [
    'http://localhost:3100/gun'
];
const gun = Gun(peers);
gun.get('docs').put({name: 'Test'});

**Comment by amark** [comment]
@kavaro thanks for reporting this. This breaking change happened during v0.7.x -> v0.8.x.

The community agreed that gun's `context` or `msg` (or sometimes previously called `at`) should not be responsible for determining which gun instance is used.

For example, old design:

```
Gun.on('put', function(msg){
  var gun = msg.gun;
  // this determines which gun instance was used
});
```

New design (which I dislike, but the community thought it was more explicit/clear and would lead to less bugs, so I complied) is like:

```
Gun.on('opt', function(ctx){
  ctx.on('put', function(msg){
    // do stuff
    ctx.on('in', ack);
  });
});
```

This was the last breaking change in gun and was planned on for about a month in advance. It also may be the last breaking change in gun (no further breaking changes are planned).

I thought Spencer had upgraded this, so I didn't know it was still broken.

It should be an easy fix but I'm swamped right now :( and won't be able to get to it for a while.

Anywho, what are you trying to build? :)

**Comment by sjones6** [comment]
Thanks for reporting this trouble. 

It'll be a bit before I can tackle this if @PsychoLlama doesn't nail it down first. 

Gun-Mongo and Gun-Mongo-key should both be working fine with the current version of Gun. If not, please do open up an issue for those. 

@amark I think we patched this up in flint but not sure we got Gun-level.

**Comment by sjones6** [comment]
See #39 .

**Comment by sjones6** [comment]
PR #39 merged and closing this out.

@kavaro , kindly re-open this issue if you continue to have troubles.
