### ISSUE TITLE
Update docs for Level v2

### ISSUE THREAD

**Issue by PsychoLlama** [PsychoLlama/gun-level#40]
Level v2 is out! Woooohooooo!!

Thankfully, there's nothing which breaks the adapter functionality.

A few packages have been moved around though, so the readme will need to be updated. General gist for people finding this issue:

```diff
- var levelup = require('levelup')
- var level = levelup('name', {
+ var leveldb = require('level')
+ var level = leveldb('name', {
    valueEncoding: 'json',
-   db: require('leveldown'),
  })
```

Pull out `leveldown` and `levelup` and replace them with `level`. The rest is _mostly_ the same.

For people using different level backends, it looks like the `encoding-down` package makes it work the same as it did in `v1`. Here's an example:

> **Note:** this code hasn't been vetted. I'm pretty sure this is how it works though.
```js
var levelup = require('levelup')
var down = require('some-other-backend-to-level')
var encoding = require('encoding-down')
var level = levelup('db-name', {
  valueEncoding: 'json',
  db: encoding(down),
})
```

[Check out the level changelog](https://github.com/Level/levelup/blob/master/CHANGELOG.md#200--october-2017) for more details. They know more about the changes than I do :wink:

**Comment by sjones6** [comment]
PR #41 up to address this.

Pretty sure the code should look like this (`valueEncoding` should be passed to the encoding function rather than the `levelup` function).
```javascript
var levelup = require('levelup')
var down = require('some-other-backend-to-level')
var encoding = require('encoding-down')
const levelDB = levelup(
	encoding(
		down('data'),
		{ valueEncoding: 'json' }
	)
)
```

**Comment by sjones6** [comment]
#41 merged. Docs should now be updated with instructions to support level up v1 and 2. Closing this out.

**Comment by amark** [comment]
You are a hero!
