### ISSUE TITLE
Not able to use on windows (10)

### ISSUE THREAD

**Issue by Stefdv** [PsychoLlama/gun-level#6]
It seems like levelDb support for Windows is discontinued.
https://github.com/google/leveldb/issues?utf8=%E2%9C%93&q=windows

**Comment by PsychoLlama** [comment]
Ugh, that's a bummer. So I tried installing it on a windows machine I have, and it failed at the [LevelDOWN](https://www.npmjs.com/package/leveldown) build, but I was able to install [LevelUP](https://www.npmjs.com/package/levelup) without any issues... based on their ecosystem, it should be possible to swap the `down` module with a windows-compatible layer.
Currently, you should be able to remove the `leveldown` dependency in the package.json file and pass [another module](https://github.com/Level/levelup/wiki/Modules#storage) as the `down` option, though I'm hoping to make this painless in the future.

```javascript
var db_plugin = require('a-level-down-plugin')
var Gun = require('gun-level')

var gun = new Gun({
  level: {
    down: db_plugin
  }
})
```

gun-level's about due for a refactor, and may see the leveldown module dropped as a dependency, especially with the sad news about windows :unamused:

**Comment by PsychoLlama** [comment]
Hey @Stefdv, I've just made a new release (v4.0.0) that adds windows compatibility and better browser support. The syntax is a bit different in this version.

**Previous syntax**
```javascript
var Gun = require('gun-level')
var gun = new Gun({
  level: { share: true, path: 'data/' }
})
```

**Revised syntax**
```javascript
var Gun = require('gun')
require('gun-level')

// Create a levelDB instance
var levelup = require('levelup')
var down = require('<level-module>-down')
var db = levelup('data/', { db: down })

// Pass it to gun
var gun = new Gun({ level: db })
```

It's a bit more verbose, but this way you get full control over your level setup, since `levelup`/`leveldown` are no longer dependencies. I set up a simple chat app on a windows computer and everything seems to be working great on the new version.

> For the windows app I'm using [`jsondown`](https://github.com/toolness/jsondown). Should be able to swap it for others.

Closing for now, feel free to reopen if you run into problems.

**Comment by Stefdv** [comment]
@PsychoLlama  woow  tx man. I've extended my vacation, but will try it next week. :)

**Comment by PsychoLlama** [comment]
Sure thing, @Stefdv! Thanks for reporting the issue. Enjoy the vacation :wink:

**Comment by Stefdv** [comment]
@PsychoLlama  would you mind sharing your (windows) chat app...just so i can see how you set everything up...?
I must be doing something wrong

**Comment by PsychoLlama** [comment]
Hey @Stefdv! Sorry for the delay, glad to hear it's working now for ya. I've put the chat app in [a Gist](https://gist.github.com/PsychoLlama/f30b2dac2b3b624fd5a6bf98e7d0c442) for reference.

If it's any help, I've discovered the [sqldown](https://github.com/calvinmetcalf/SQLdown) module, which works with [SQLite3](https://www.npmjs.com/package/sqlite3) (comparable to leveldown), postgres, or mysql. SQLite3 is my personal fav, and works on most platforms (including windows). A tad more compelling than jsondown :wink:

Lemme know if you run into any more issues! Thanks for the feedback :grinning:
